### ISSUE TITLE
Dataset peptide_fdr does not exist for group 

### ISSUE THREAD

**Issue by treitpeter** [MannLabs/alphapept#315] opened 2021-09-01 10:00 UTC
Running 311 metaproteome files against CaZy database, machine 10.31.1

error message: 

'''Dataset peptide_fdr does not exist for group / of <HDF_File D:\\Dari\\Dari_RAWs_Main\\20210513_EXPL0_PeTr_SA_T760_1285_20210528083210.ms_data.hdf>.'''

**Version 
 - OS:  Windows
 - Version 0.3.26
 - Installation Type  Python

**Comment by k-Vartika** [comment] 2022-04-05 08:58
I get the same error (data consists of fractions, DDA mode) for Alphapept version 0.4.2. 
error: '''Dataset peptide_fdr does not exist for group / of <HDF_File E:\\QPC_Analysis\\AlphaPept\\XXX\\XXX.ms_data.hdf>.'''

```
workflow:
  continue_runs: false
  create_database: true
  import_raw_data: true
  find_features: true
  search_data: true
  recalibrate_data: true
  align: true
  match: true
  lfq_quantification: true
```

**Comment by straussmaximilian** [comment] 2022-04-14 09:38
This is a general error which could have various reasons. Mostly it is because AlphaPept did not find any results.
The cause for @treitpeter should be fixed, for @animesh this was probably because of DIA.

For @k-Vartika I will investigate.

Closing this for now.

**Closed by straussmaximilian** 2022-04-14 09:38 UTC
